### PR TITLE
add a prop for the function that filters the list (function onSearch in Dropdown component)

### PR DESCRIPTION
**Pull request by antonycms**
add a prop for the function that filters the list (function onSearch in Dropdown component)

example:
<Dropdown  searchFunction={(inputText, labelText) => inputText === labelText}  />

### CODE REVIEW

**Comment by hoaphantn7604** [comment]
hi @antonycms ,
Thank you!
We can discuss this searchFunction.
Why did you add searchFunction how does it help your project.

**Comment by antonycms** [comment]
hello @hoaphantn7604, first thanks for the lib, it is of great help in the development.
The searchFunction prop was needed to define a more sensitive filter in a task that was passed to me, basically I created a callback that checks keywords in any order within the label string, the default callback only checks words in order.
As my filter was something very specific, I thought it best to just add a prop where it would be possible to define a custom callback.

**Comment by hoaphantn7604** [comment]
hi @antonycms,
Thank you!
Search function is used for Dropdown and MultiSelect.
I added searchQuery to MultiSelect.
Document:
```js
| searchQuery        | (keyword: string, labelValue: string) => Boolean     | No        | Callback used to filter the list of items                           |
```
Please install later version 1.6.0.
I will close merge request.

**Comment by Vijay-CareAllianz** [comment]
hi @hoaphantn7604 I would like to search from db after every letter user enters or after a word. How can i achieve this?

**Pull request closed without merging**
